---
schema:
  procedures: {}
  tables:
    article:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - category
          match_type: ''
          name: article_fk_category
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: category
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - source_feed
          match_type: ''
          name: article_fk_source_feed
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: feed
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - submitting_user
          match_type: ''
          name: article_fk_submitting_user
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: user
          type: FOREIGN KEY
      fields:
        category:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: category
          order: 4
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        source_feed:
          data_type: int
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: source_feed
          order: 2
          size:
            - 0
        submitting_user:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: submitting_user
          order: 3
          size:
            - 0
      indices:
        - fields:
            - category
          name: article_idx_category
          options: []
          type: NORMAL
        - fields:
            - source_feed
          name: article_idx_source_feed
          options: []
          type: NORMAL
        - fields:
            - submitting_user
          name: article_idx_submitting_user
          options: []
          type: NORMAL
      name: article
      options: []
      order: 5
    category:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 0
      indices: []
      name: category
      options: []
      order: 1
    data:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - name
          match_type: ''
          name: data_name_unique
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        data:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: data
          order: 3
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: name
          order: 2
          size:
            - 0
      indices: []
      name: data
      options: []
      order: 2
    feed:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - submitting_user
          match_type: ''
          name: feed_fk_submitting_user
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: user
          type: FOREIGN KEY
      fields:
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        submitting_user:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: submitting_user
          order: 2
          size:
            - 0
      indices:
        - fields:
            - submitting_user
          name: feed_idx_submitting_user
          options: []
          type: NORMAL
      name: feed
      options: []
      order: 4
    user:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
      indices: []
      name: user
      options: []
      order: 3
    vote:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - article_id
            - user_id
          match_type: ''
          name: vote_combo_unique
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - article_id
          match_type: ''
          name: vote_fk_article_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: article
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: vote_fk_user_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: user
          type: FOREIGN KEY
      fields:
        article_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: article_id
          order: 2
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        user_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: user_id
          order: 3
          size:
            - 0
      indices:
        - fields:
            - article_id
          name: vote_idx_article_id
          options: []
          type: NORMAL
        - fields:
            - user_id
          name: vote_idx_user_id
          options: []
          type: NORMAL
      name: vote
      options: []
      order: 6
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    package: &1 !!perl/hash:XT::Schema
      class_mappings:
        DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult: __VERSION
        XT::Schema::Result::Article: Article
        XT::Schema::Result::Category: Category
        XT::Schema::Result::Data: Data
        XT::Schema::Result::Feed: Feed
        XT::Schema::Result::User: User
        XT::Schema::Result::Vote: Vote
      source_registrations:
        Article: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            category:
              data_type: int
              is_nullable: 0
              is_numeric: 1
            id:
              data_type: int
              is_auto_increment: 1
              is_nullable: 0
              retreive_on_insert: 1
            source_feed:
              data_type: int
              is_nullable: 1
              is_numeric: 1
            submitting_user:
              data_type: int
              is_nullable: 0
              is_numeric: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - source_feed
            - submitting_user
            - category
          _primaries: &2
            - id
          _relationships:
            article_has_category:
              attrs: {}
              class: Category
              cond:
                foreign.id: self.category
              source: Category
            article_has_feed:
              attrs: {}
              class: Feed
              cond:
                foreign.id: self.source_feed
              source: Feed
            article_has_submitting_user:
              attrs: {}
              class: User
              cond:
                foreign.id: self.submitting_user
              source: User
          _unique_constraints:
            primary: *2
          name: article
          result_class: XT::Schema::Result::Article
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Article
        Category: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            id:
              data_type: int
              is_auto_increment: 1
              is_nullable: 0
              retrieve_on_insert: 1
            name:
              data_type: text
              is_nullable: 0
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - name
          _primaries: &3
            - id
          _relationships: {}
          _unique_constraints:
            primary: *3
          name: category
          result_class: XT::Schema::Result::Category
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Category
        Data: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            data:
              _inflate_info:
                deflate: !!perl/code '{ "DUMMY" }'
                inflate: !!perl/code '{ "DUMMY" }'
              data_type: text
              is_nullable: 0
              serializer_class: YAML
            id:
              data_type: int
              is_auto_increment: 1
              retrieve_on_insert: 1
            name:
              data_type: text
              is_nullable: 0
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - name
            - data
          _primaries: &4
            - id
          _relationships: {}
          _unique_constraints:
            data_name_unique:
              - name
            primary: *4
          name: data
          result_class: XT::Schema::Result::Data
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Data
        Feed: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            id:
              data_type: int
              is_auto_increment: 1
              is_nullable: 0
              retrieve_on_insert: 1
            submitting_user:
              data_type: int
              is_nullable: 0
              retreive_on_insert: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - submitting_user
          _primaries: &5
            - id
          _relationships:
            feed_has_submitting_user:
              attrs: {}
              class: User
              cond:
                foreign.id: self.submitting_user
              source: User
          _unique_constraints:
            primary: *5
          name: feed
          result_class: XT::Schema::Result::Feed
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Feed
        User: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            id:
              data_type: int
              is_auto_increment: 1
              is_nullable: 0
              retrieve_on_insert: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - id
          _primaries: &6
            - id
          _relationships: {}
          _unique_constraints:
            primary: *6
          name: user
          result_class: XT::Schema::Result::User
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: User
        Vote: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            article_id:
              data_type: int
              is_nullable: 0
              retrieve_on_insert: 1
            id:
              data_type: int
              is_auto_increment: 1
              is_nullable: 0
              retrieve_on_insert: 1
            user_id:
              data_type: int
              is_nullable: 0
              retrieve_on_insert: 1
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - article_id
            - user_id
          _primaries: &7
            - id
          _relationships:
            vote_has_article:
              attrs: {}
              class: Article
              cond:
                foreign.id: self.article_id
              source: Article
            vote_has_user:
              attrs: {}
              class: User
              cond:
                foreign.id: self.user_id
              source: User
          _unique_constraints:
            primary: *7
            vote_combo_unique:
              - article_id
              - user_id
          name: vote
          result_class: XT::Schema::Result::Vote
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Vote
        __VERSION: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            ddl:
              data_type: text
              is_nullable: 1
            id:
              data_type: int
              is_auto_increment: 1
            upgrade_sql:
              data_type: text
              is_nullable: 1
            version:
              data_type: varchar
              size: 50
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - version
            - ddl
            - upgrade_sql
          _primaries: &8
            - id
          _relationships: {}
          _unique_constraints:
            dbix_class_deploymenthandler_versions_version:
              - version
            primary: *8
          name: dbix_class_deploymenthandler_versions
          result_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult
          resultset_attributes: {}
          resultset_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet
          schema: *1
          source_name: __VERSION
      storage: !!perl/hash:DBIx::Class::Storage::DBI
        _connect_info:
          - dsn: dbi:SQLite:/tmp/XT.sqlite
        _dbh_details: {}
        _dbh_gen: 0
        _dbi_connect_info:
          - dbi:SQLite:/tmp/XT.sqlite
          - ~
          - ~
          - &9
            AutoCommit: 1
            PrintError: 0
            RaiseError: 1
            ShowErrorStatement: 1
        _dbic_connect_attributes: *9
        _in_do_block: 0
        _sql_maker: ~
        _sql_maker_opts: {}
        savepoints: []
        schema: *1
        transaction_depth: 0
    sources:
      - Data
      - User
      - Feed
      - Category
      - Vote
      - Article
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11016
